name: Restaurant-api-cd

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release
        
      - name: publish
        run: dotnet publish ./src/Restaurants.API/Restaurants.API.csproj -c Release -o ./api --no-build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: api-artifact
          path:  ./api   

  deploy-dev:
     environment:
       name: 'dev'
       url: ${{steps.dev-env.outputs.webapp-url}}
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Download a Build Artifact
         uses: actions/download-artifact@v7.0.0
         with:
           name: api-artifact
       - name: Azure WebApp
         uses: Azure/webapps-deploy@v2.2.17
         id: dev-env
         with:
          app-name: restaurant-api-dev
          publish-profile: ${{secrets.PUBLISH_PROFILE_DEV}}
          
  deploy-prod:
     environment:
      name: 'prod'
      url: ${{steps. prod-env.outputs.webapp-url}}
     runs-on: ubuntu-latest
     needs: deploy-dev
     steps:
       - name: Download a Build Artifact
         uses: actions/download-artifact@v7.0.0
         with:
           name: api-artifact
       - name: Azure WebApp
         uses: Azure/webapps-deploy@v2.2.17
         id: prod-env
         with:
          app-name: restaurants-api-prod
          publish-profile: ${{secrets.PUBLIC_PROFILE_PROD}}
          
  

